# Generated by Django 5.0.1 on 2026-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvfile',
            name='file_cs',
            field=models.FileField(null=True, upload_to='cv_files/'),
        ),
        migrations.AddField(
            model_name='cvfile',
            name='file_en',
            field=models.FileField(null=True, upload_to='cv_files/'),
        ),
    ]
