# Generated by Django 5.0.1 on 2026-07-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cvfile_file_cs_cvfile_file_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='photos/thumbnails/'),
        ),
    ]
