# Generated by Django 5.0.1 on 2024-02-16 09:23

import django.core.validators
import django.db.models.deletion
import markdownfield.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(max_length=100)),
                ("position_en", models.CharField(max_length=100, null=True)),
                ("position_cs", models.CharField(max_length=100, null=True)),
                ("description", markdownfield.models.MarkdownField()),
                ("description_en", markdownfield.models.MarkdownField(null=True)),
                ("description_cs", markdownfield.models.MarkdownField(null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("position_en", models.CharField(max_length=100, null=True)),
                ("position_cs", models.CharField(max_length=100, null=True)),
                ("description", markdownfield.models.MarkdownField()),
                ("description_en", markdownfield.models.MarkdownField(null=True)),
                ("description_cs", markdownfield.models.MarkdownField(null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("identifier", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=32)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("about_me", markdownfield.models.MarkdownField()),
                ("about_me_en", markdownfield.models.MarkdownField(null=True)),
                ("about_me_cs", markdownfield.models.MarkdownField(null=True)),
                ("driver_license", models.CharField(max_length=32)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=255)),
                (
                    "headshot",
                    models.ImageField(blank=True, null=True, upload_to="headshots/"),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_cs", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="photos/")),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_cs", models.CharField(max_length=100, null=True)),
                ("short_description", models.CharField(max_length=100)),
                ("short_description_en", models.CharField(max_length=100, null=True)),
                ("short_description_cs", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_cs", models.TextField(null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="TypeSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_cs", models.CharField(max_length=100, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "LinkedIn"),
                            (1, "Facebook"),
                            (2, "Instagram"),
                            (3, "GitHub"),
                        ]
                    ),
                ),
                ("url", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.personalinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_cs", models.CharField(max_length=100, null=True)),
                (
                    "description",
                    markdownfield.models.MarkdownField(blank=True, null=True),
                ),
                (
                    "description_en",
                    markdownfield.models.MarkdownField(blank=True, null=True),
                ),
                (
                    "description_cs",
                    markdownfield.models.MarkdownField(blank=True, null=True),
                ),
                (
                    "percent",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "type_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.typeskill"
                    ),
                ),
            ],
            options={
                "ordering": ["-title"],
            },
        ),
    ]
