# Generated by Django 5.0.1 on 2024-01-30 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="personalinfo",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="name",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="about_me",
            field=models.TextField(default="empty"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="driver_license",
            field=models.CharField(default="no", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="first_name",
            field=models.CharField(default="Pepe", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="headshot",
            field=models.ImageField(blank=True, null=True, upload_to="headshots/"),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="identifier",
            field=models.CharField(default="temp", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="last_name",
            field=models.CharField(default="The Frog", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="phone",
            field=models.CharField(default="777123456", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="title",
            field=models.CharField(default="Ing", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "type_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.typeskill"
                    ),
                ),
            ],
            options={
                "ordering": ["-title"],
            },
        ),
    ]
