# Generated by Django 5.0.1 on 2024-01-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_education_id_alter_job_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="description",
        ),
    ]
