# Generated by Django 5.0.1 on 2024-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_skill_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
