# Generated by Django 5.0.1 on 2024-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_skill_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description_cs",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="description_en",
            field=models.TextField(null=True),
        ),
    ]
