# Generated by Django 5.0.1 on 2024-02-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_skill_description_cs_skill_description_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
