# Generated by Django 5.0.1 on 2024-02-01 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_personalinfo_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="typeskill",
            name="order",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
