# Generated by Django 5.0.1 on 2024-02-02 16:58

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="about_me_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="about_me",
            field=markdownfield.models.MarkdownField(rendered_field="text_rendered"),
        ),
    ]
