# Generated by Django 5.0.1 on 2024-02-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_personalinfo_about_me_rendered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="about_me_rendered",
        ),
    ]
