# Generated by Django 5.0.1 on 2024-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_personalinfo_about_me_rendered"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
