# Generated by Django 5.0.1 on 2024-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_title_job_company_alter_education_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
