# Generated by Django 5.0.1 on 2024-02-03 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_education_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "LinkedIn"),
                            (1, "Facebook"),
                            (2, "Instagram"),
                            (3, "GitHub"),
                        ]
                    ),
                ),
                ("url", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.personalinfo",
                    ),
                ),
            ],
        ),
    ]
