# Generated by Django 5.0.1 on 2024-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_socialmediaaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="title_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
