# Generated by Django 5.0.1 on 2024-02-10 11:24

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_skill_title_cs_skill_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="description_cs",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="description_en",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="position_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="position_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="description_cs",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="description_en",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="position_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="position_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="about_me_cs",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="about_me_en",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="title_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_cs",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="title_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="typeskill",
            name="title_cs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="typeskill",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
