# Generated by Django 5.0.1 on 2024-02-10 13:28

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_education_description_cs_education_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description_rendered",
            field=markdownfield.models.RenderedMarkdownField(default="bruhh"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=markdownfield.models.MarkdownField(
                rendered_field="description_rendered"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_cs",
            field=markdownfield.models.MarkdownField(
                null=True, rendered_field="description_rendered"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_en",
            field=markdownfield.models.MarkdownField(
                null=True, rendered_field="description_rendered"
            ),
        ),
    ]
