# Generated by Django 5.0.1 on 2024-02-10 13:40

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_job_description_rendered_alter_job_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="description_rendered",
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=markdownfield.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_cs",
            field=markdownfield.models.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_en",
            field=markdownfield.models.MarkdownField(null=True),
        ),
    ]
