# Generated by Django 5.0.1 on 2024-02-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_job_description_rendered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="short_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
